name: "lint"
description: "setup python 3.10 and execute flake8 linting"

runs:
  using: "composite"
  steps:
  - name: Set up Python 3.12
    uses: actions/setup-python@v4
    with:
      python-version: '3.12.4'
  - name: install dev dependencies
    run: pip install .[dev,wandb]
    shell: bash
  - name: run linting
    run: make lint-check
    shell: bash
  - name: Check docs building
    run: make docs-build
    shell: bash
  - name: Test with pytest
    run: |
      make test-unit
    shell: bash
