name: "bump version"
description: "bump our version in the repo and push the change"

runs:
  using: "composite"
  steps:
  - name: configure git
    run: |
      git config --global user.email "devs@qognitiveai.com"
      git config --global user.name "qcog_bot"
    shell: bash
  - name: push to repo
    run: |
      git tag $(python -m setuptools_scm --strip-dev)
    shell: bash

