name: "bump version"
description: "bump our version in the repo and push the change"

runs:
  using: "composite"
  steps:
  - name: install bumpversion
    run: |
      pip install bump2version
    shell: bash
  - name: configure git
    run: |
      git config --global user.email "devs@qognitiveai.com"
      git config --global user.name "qcog_bot"
    shell: bash
  - name: bump the version
    run: |
      bump2version patch --allow-dirty
    shell: bash
  - name: push to repo
    run: |
      mkdir -p ~/.ssh
      echo "${QCOG_DEPLOY_PUSH_KEY}" > ~/.ssh/id_rsa
      chmod 600 ~/.ssh/id_rsa
      git push git@github.com:${GITHUB_REPOSITORY}
      git push --tags git@github.com:${GITHUB_REPOSITORY}
    shell: bash
