name: "Integration tests"
description: "Performs a tests against mocked services"

runs:
  using: "composite"
  steps:
  - name: Set up Python 3.12
    uses: actions/setup-python@v4
    with:
      python-version: '3.12.4'
  - name: install dev dependencies
    run: pip install .[dev] .[wandb]
    shell: bash
  - name: Integration Tests
    run: |
      make test-integration
    shell: bash
