name: Run On PR against main

permissions:
    id-token: write   # This is required for requesting the JWT
    contents: read    # This is required for actions/checkout

on:
    pull_request:
        branches:
            - main

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
        - name: checkout code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Python Setup
          uses: actions/setup-python@v4
          with:
            python-version: '3.12.4'
        - name: Build schema
          uses: ./.github/actions/build-schema
        - name: Setup python, Lint Code and test
          uses: ./.github/actions/setup_lint_and_test
    integration-tests:
        runs-on: ubuntu-latest
        steps:
        - name: checkout code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Python Setup
          uses: actions/setup-python@v4
          with:
              python-version: '3.12.4'
        - name: Build schema
          uses: ./.github/actions/build-schema
        - name: Setup python, Integration Tests
          uses: ./.github/actions/integration_tests
